title: Steam Deck Pirates' Cove
description: A comprehensive guide to sailing the high seas on your Steam Deck.
url: "https://livinin82.github.io/steam-deck-pirates"
baseurl: "/steam-deck-pirates"
markdown: kramdown
highlighter: rouge

# Enable search
search_enabled: true

collections:
  docs:
    output: true
    permalink: /:collection/:name

permalink: pretty

defaults:
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: default

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - scripts/
  - Gemfile*

# Simple nav configuration (optional manual ordering override)
nav_parents_order:
  - Info About Steam Deck
  - Apps you NEED TO have installed
  - Guides for installing games
  - Guides for Proton/Wine
  - Guides for emulators and roms
  - Cracks/DLC/Updates
  - Common Questions

sass:
  style: compressed

