theme: just-the-docs
title: Steam Deck Pirates' Cove
description: A comprehensive guide to sailing the high seas on your Steam Deck.
url: "https://livinin82.github.io/steam-deck-pirates"
color_scheme: custom-dark

# Enable search
search_enabled: true

# Just the Docs settings
just_the_docs:
  # Enable table of contents
  toc:
    enabled: true
    title: "On this page"
  # Enable mermaid diagrams
  mermaid:
    enabled: true

